---
- name: Install the Python MySQLdb module
  apt: name=python-mysqldb state=installed
  become: yes
  become_method: sudo

- name: Remove Anonymous MySQL users
  action: mysql_user name='' state='absent'

- name: Create database user
  mysql_user: name={{ mysql_user }} password={{ mysql_password }} priv=*.*:ALL state=present
  when: mysql_user != ''