---
- name: Check if solr_home is already set up.
  stat: "path={{ solr_home }}/solr.xml"
  register: solr_example

- name: Ensure solr_home directory exists.
  file:
    path: "{{ solr_home }}"
    state: directory
    owner: "{{ solr_user }}"
    group: "{{ solr_user }}"
    mode: 0755
  when: not solr_example.stat.exists

- name: Ensure Solr home files are owned by the solr_user.
  file:
    path: "{{ solr_home }}"
    owner: "{{ solr_user }}"
    group: "{{ solr_user }}"
    recurse: yes
  when: not solr_example.stat.exists
