---
- name: Install Apache
  apt: name=apache2 state=present

- name: Remove default virtual host
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  notify:
    - reload apache

- name: Create new virtual host entry for Bianchi
  template: 
    src=virtual-hosts.conf.j2 
    dest=/etc/apache2/sites-available/bianchi.conf
  notify:
    - reload apache

- name: Enable virtual host entry for Bianchi
  file:
    src=/etc/apache2/sites-available/bianchi.conf
    dest=/etc/apache2/sites-enabled/bianchi.conf
    state=link
  notify:
    - reload apache